../build.linux/nachos -f
../build.linux/nachos -mkdir /t0
../build.linux/nachos -mkdir /t1
../build.linux/nachos -mkdir /t2
../build.linux/nachos -mkdir /t3
../build.linux/nachos -mkdir /t4
../build.linux/nachos -mkdir /t5
../build.linux/nachos -mkdir /t6
../build.linux/nachos -mkdir /t7
../build.linux/nachos -mkdir /t8
../build.linux/nachos -mkdir /t9
../build.linux/nachos -mkdir /t10
../build.linux/nachos -mkdir /t11
../build.linux/nachos -mkdir /t12
../build.linux/nachos -mkdir /t13
../build.linux/nachos -mkdir /t14
../build.linux/nachos -mkdir /t15
../build.linux/nachos -mkdir /t16
../build.linux/nachos -mkdir /t17
../build.linux/nachos -mkdir /t18
../build.linux/nachos -mkdir /t19
../build.linux/nachos -mkdir /t20
../build.linux/nachos -mkdir /t21
../build.linux/nachos -mkdir /t22
../build.linux/nachos -mkdir /t23
../build.linux/nachos -mkdir /t24
../build.linux/nachos -mkdir /t25
../build.linux/nachos -mkdir /t26
../build.linux/nachos -mkdir /t27
../build.linux/nachos -mkdir /t28
../build.linux/nachos -mkdir /t29
../build.linux/nachos -mkdir /t30
../build.linux/nachos -mkdir /t31
../build.linux/nachos -mkdir /t32
../build.linux/nachos -mkdir /t33
../build.linux/nachos -mkdir /t34
../build.linux/nachos -mkdir /t35
../build.linux/nachos -mkdir /t36
../build.linux/nachos -mkdir /t37
../build.linux/nachos -mkdir /t38
../build.linux/nachos -mkdir /t39
../build.linux/nachos -mkdir /t40
../build.linux/nachos -mkdir /t41
../build.linux/nachos -mkdir /t42
../build.linux/nachos -mkdir /t43
../build.linux/nachos -mkdir /t44
../build.linux/nachos -mkdir /t45
../build.linux/nachos -mkdir /t46
../build.linux/nachos -mkdir /t47
../build.linux/nachos -mkdir /t48
../build.linux/nachos -mkdir /t49
../build.linux/nachos -mkdir /t50
../build.linux/nachos -mkdir /t51
../build.linux/nachos -mkdir /t52
../build.linux/nachos -mkdir /t53
../build.linux/nachos -mkdir /t54
../build.linux/nachos -mkdir /t55
../build.linux/nachos -mkdir /t56
../build.linux/nachos -mkdir /t57
../build.linux/nachos -mkdir /t58
../build.linux/nachos -mkdir /t59
../build.linux/nachos -mkdir /t60
../build.linux/nachos -mkdir /t61
../build.linux/nachos -mkdir /t62
../build.linux/nachos -mkdir /t63
../build.linux/nachos -lr /
echo "========================================="
